# Generated by Django 2.1.3 on 2018-11-25 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='description',
        ),
    ]
